USE [master]
GO

/****** Object:  Database [InfinityStoreDB]    Script Date: 8/30/2020 10:44:20 PM ******/
CREATE DATABASE [InfinityStoreDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InfinityStoreDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InfinityStoreDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InfinityStoreDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InfinityStoreDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InfinityStoreDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InfinityStoreDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET RECOVERY FULL 
GO

ALTER DATABASE [InfinityStoreDB] SET  MULTI_USER 
GO

ALTER DATABASE [InfinityStoreDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InfinityStoreDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InfinityStoreDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InfinityStoreDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InfinityStoreDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InfinityStoreDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InfinityStoreDB] SET  READ_WRITE 
GO


